version: '3'

name: template-hono-prisma-kysely

services:
  # Postgres
  pg:
    image: postgres:15.3-alpine
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./databases/pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # Test Postgres
  test-pg:
    image: postgres:15.3-alpine
    ports:
      - '${TEST_DB_PORT}:5432'
    volumes:
      - ./databases/test-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4:6
    ports:
      - '${PGADMIN_PORT}:5050'
    volumes:
      - ./databases/pg/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - pg
